//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@components/nav";
import { ToastContainer } from "react-toastify";
import {  ThemeProvider } from "@providers/ThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Addressing System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          <ThemeProvider>
              {/* <div className="flex flex-col min-h-screen"> */}
                <Nav />
                <ToastContainer
                  position="top-center"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick={false}
                  rtl={false}
                  // pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                  // transition={Bounce}
                  //className={mt-20}
                />
                {children}
          </ThemeProvider>

      </body>
    </html>
  );
}
